language: c

before_script:
- python --version
- pip install --user pip
- sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6D1D8367A3421AFB
- sudo add-apt-repository -y ppa:team-gcc-arm-embedded/ppa
- sudo apt update
- sudo apt install scons
- scons --version
- sudo apt install gcc-arm-embedded
- arm-none-eabi-gcc --version
- sudo apt install doxygen
- doxygen --version

script:
- mkdir -p ./build/doc/
